### ISSUE TITLE
encfs breaks on high IO

### ISSUE THREAD

**Issue by axet** [vgough/encfs#109] opened 2015-08-26 10:07 UTC
Hello!

I'm using encfs on Mac Yosimite 10.10.5 with my private folder. This folder includes a lot of small files (source code). And working with eclipse or git on encrupted folder can cause a file lost/lock/corrupt file system.

This bug easy to reproduce. Just create encfs folder and clone a source tree into it. You will get a few errros, then removing a folder cause another on encfs space.

`# git clone http://github.com/golang/go gg`

https://trac.macports.org/ticket/48705

**Comment by rfjakob** [comment] 2015-08-26 10:36
I tried to reproduce this. I got an "Interrupted system call" message, but `git fsck` came back clean.
Behind the scenes, this seems to be caused in a bug in OSXFUSE, https://github.com/osxfuse/osxfuse/issues/228 

	$ git clone http://github.com/golang/go gg
	Cloning into 'gg'...
	remote: Counting objects: 223712, done.
	error: unable to open object pack directory: ./gg/.git/objects/pack: Interrupted system call
	remote: Total 223712 (delta 0), reused 0 (delta 0), pack-reused 223712
	Receiving objects: 100% (223712/223712), 77.44 MiB | 2.10 MiB/s, done.
	Resolving deltas: 100% (178998/178998), done.
	Checking connectivity... done.
	Checking out files: 100% (4914/4914), done.
	$ cd gg
	$ git fsck
	Checking object directories: 100% (256/256), done.
	Checking objects: 100% (223712/223712), done.
	Checking connectivity: 223712, done.

**Comment by rfjakob** [comment] 2015-08-26 10:43
Ok, on the second clone run, it failed:

	$ git clone http://github.com/golang/go gg
	Cloning into 'gg'...
	remote: Counting objects: 223712, done.
	remote: Total 223712 (delta 0), reused 0 (delta 0), pack-reused 223712
	Receiving objects: 100% (223712/223712), 77.44 MiB | 2.28 MiB/s, done.
	Resolving deltas: 100% (178999/178999), done.
	Checking connectivity... done.
	error: unable to create file test/eof.go (File exists)
	error: unable to create file test/printbig.go (File exists)
	Checking out files: 100% (4914/4914), done.
	fatal: unable to checkout working tree
	warning: Clone succeeded, but checkout failed.
	You can inspect what was checked out with 'git status'
	and retry the checkout with 'git checkout -f HEAD'

**Comment by axet** [comment] 2015-08-26 10:44
sometimes it succeed. glad you tried it second time :)

now try to remove gg folder. it failed again.

**Comment by rfjakob** [comment] 2015-08-26 10:49
Indeed:

	$ rm -Rf gg
	rm: gg/test: Directory not empty
	rm: gg: Directory not empty

**Comment by axet** [comment] 2015-08-26 11:13
this script will help you remove this folder ;)

https://github.com/axet/homebin/tree/mac/encfsopen

**Comment by rfjakob** [comment] 2015-10-30 21:54
Sorry for leaving this ticket idle for so long, but ultimately I think these are bugs in the FUSE layer. What are you using? OSXFUSE?

**Comment by axet** [comment] 2015-10-31 04:59
osxfuse @2.8.2

**Comment by jkaberg** [comment] 2015-11-03 15:09
Just thought I'd let you know I'm seeing this one as well, lots of minor files (around 500k) crashes with I/O error

Any known workaround?

**Comment by rfjakob** [comment] 2015-11-03 15:42
I think the only way to make progress here is to find a volunteer who can
compile and test changes on a osx.
The mac I used to reproduce it was not mine.

**Comment by jkaberg** [comment] 2015-11-03 20:59
Actully, I'm seeing this on linux

**Comment by rfjakob** [comment] 2015-11-03 21:01
Really? Well, that's bad, but easier to debug for me.
How can I trigger it?

**Comment by jkaberg** [comment] 2015-11-03 21:08
About windows support, perhaps this? 

https://github.com/dokan-dev/dokany

Will require some work tho..

**Comment by jkaberg** [comment] 2015-11-03 21:10
Just mount as you would with encfs, and copy large amounts of files around 5-30MB ea to the unencrypted mount 

You should get the error pretty fast (like 1-3 min)

**Comment by rfjakob** [comment] 2015-11-03 22:25
Yes, got it, and I have a core dump. It crashes with a segmentation violation in `memcpy` in `cacheReadOneBlock`. Full backtrace: https://gist.github.com/rfjakob/07cba2554984fae9e5ed

I noticed that both Thread 1 and Thread 11 are in `cacheReadOneBlock` when this happens. Race condition?

@vgough Looking at `cacheReadOneBlock` I wonder if it needs some locking.

**Comment by rfjakob** [comment] 2015-11-03 23:16
I recompiled current master with debug symbols (`cmake -DCMAKE_BUILD_TYPE=Debug ..`) and additionally started encfs with `-s` to make it single-threaded. It still crashes, which means it is probably not a race condition, but I got a better backtrace: https://gist.github.com/rfjakob/4bea2186b101cd15443a

I am puzzled how `result` can be `-1` at this point.

**Comment by rfjakob** [comment] 2015-11-03 23:32
@jkaberg What filesystem do you see this on? Maybe tmpfs as I do?

**Comment by jkaberg** [comment] 2015-11-04 06:16
@rfjakob https://github.com/trapexit/mergerfs

**Comment by rfjakob** [comment] 2015-11-04 08:44
Could you also try to get a backtrace? I am not sure if we are seeing the same crash. Mine may be related to the tmpfs on /tmp running out of space.

Works like that:

1) Mount encfs
2) `pgrep encfs` to find the PID
3) `gdb -p PID`
4) Wait for the crash. gdb will catch it and give you a command prompt.
5) Type `bt` in the gdb prompt

**Comment by rfjakob** [comment] 2015-11-08 20:17
@jkaberg I fixed the crash I saw in commit https://github.com/rfjakob/encfs/commit/259909e213fdb637a23f0c5667a5833c4004dd90 . 

Please

    git clone -b issue109 https://github.com/rfjakob/encfs.git

and try if it fixes your problem as well.

**Comment by jkaberg** [comment] 2015-11-08 20:20
Thanks @rfjakob, I'm currently out of town and will be for some time. Will get back to you when I'm able to test this properly

**Comment by fulldecent** [comment] 2015-11-18 15:30
@rfjakob This looks good, I am +1. And I do not see any other unsafe/unchecked usage of `getSize`.

**Comment by vgough** [comment] 2015-11-23 02:24
@rfjakob can you pull your fix into encfs?

**Comment by rfjakob** [comment] 2015-11-23 07:16
Merged as https://github.com/vgough/encfs/commit/ed058fabcd20c18ea388e5f55e8260c6f79df0b1 .

**Comment by axet** [comment] 2016-01-03 14:31
I'v tried to apply ed058fabcd20c18ea388e5f55e8260c6f79df0b1 on macports source. Keep fails on 'clone'

```
axet-laptop:source axet$ git clone http://github.com/golang/go gg
Cloning into 'gg'...
remote: Counting objects: 236710, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 236710 (delta 14), reused 13 (delta 13), pack-reused 236680
Receiving objects: 100% (236710/236710), 88.76 MiB | 803.00 KiB/s, done.
Resolving deltas: 100% (189183/189183), done.
Checking connectivity... done.
error: unable to create file test/bench/go1/time_test.go (File exists)
Checking out files: 100% (5175/5175), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

axet-laptop:source axet$ rm -rf gg
rm: gg/test/bench/go1: Directory not empty
rm: gg/test/bench: Directory not empty
rm: gg/test: Directory not empty
rm: gg: Directory not empty
axet-laptop:source axet$ 
```

**Comment by pasnox** [comment] 2016-03-14 11:08
I can also reproduce that on OSXFuse/EncFS on OSX.
Anything I can help with - let me know.
I can build, test and give backtraces if needed.

**Comment by pasnox** [comment] 2016-03-14 14:34
Looks like all those errors vanished while upgrading osxfuse to latest beta (3.2.x)

**Comment by axet** [comment] 2016-09-30 16:13
Seems it fine now (mac osx 10.12, fuse 3.5.0)

**Closed** 2016-10-14 21:21 UTC
Labels: waiting for feedback
