### ISSUE TITLE
viewing encfs --reverse over NFS

### ISSUE THREAD

**Issue by spuniun** [vgough/encfs#335] opened 2017-06-25 03:12 UTC
Being unimpressed with transfer speeds of sshfs I've been trying to figure out a better solution to mount my foreign colo on my local host for the best throughput possible.
Obviously NFS has the least overhead but without getting involved in a complex kerberos setup it has not transfer encryption so I had the idea to use an encfs --reverse mount at the far end and the matching encfs at the near. However even with allow_other or allow_root on the far end, the fuse mount point gets permission denied via the NFS mount. I'm already using no_root_squash so UID/GID mapping is working as expected. Any ideas?

**Comment by TheOneValen** [comment] 2017-06-28 12:11
If its transport security you are after, why not use a proxy which adds tls?

**Comment by spuniun** [comment] 2017-06-28 12:49
I resolved the overall issue by enabling nfs4 krb5p but I'm still interested is why a fuse mount is inaccessible over nfs

**Comment by benrubson** [comment] 2017-07-03 11:15
Same as #325 ?

**Comment by samrocketman** [comment] 2017-07-03 16:44
Possibly relevant -> https://unix.stackexchange.com/questions/102617/having-trouble-exporting-fuse-via-nfs

Closing as duplicate of #325.  Please add additional comments and data to that issue.

**Closed by samrocketman** 2017-07-03 16:44 UTC
