### ISSUE TITLE
Lost files 

### ISSUE THREAD

**Issue by systeme1** [vgough/encfs#231] opened 2016-10-17 07:00 UTC
Hi, 
My problem is:
I wanted to rename the directory containing my encrypted files but I stopped during the renaming.
Now, some directories are no longer presents but exist in the directorie of encrypted files.
Please, how can that not present directories can be in the decrypted files again
Excuse my poor english, I'm not English

Best regards

Robert

**Comment by rfjakob** [comment] 2016-10-17 07:12
So you wanted to move from "disk a" to "disk b"? Now some of the files are on "disk a" and some are on "disk b"?

**Comment by systeme1** [comment] 2016-10-17 07:24
Thanks for your answer.

I wanted just change name of decrypted directory but i stop during the changing.

And some directories are not in the clear directory but are present in the encrypted directory.

**Comment by rfjakob** [comment] 2016-10-17 07:30
1) are you using paranoia mode?
2) how did you stop the rename?

**Comment by systeme1** [comment] 2016-10-17 07:36
1) I dont know, I use Cryptkeeper on Debaian Jessie

2) I stop rename by clinking on the cross of the gnome (Mate) windows.

My clear directory do not contain all the encrypted files.

Sorry, I'll be back in two hours because my job

See you later if you want.

**Comment by systeme1** [comment] 2016-10-17 10:30
Up

I'm back

**Comment by systeme1** [comment] 2016-10-17 11:04
For rename my clear directory I used my file manager Caja (my pc is under Debian 8). When renaming, I click on the right cross to stop renaming.

Now, I see only some files in my clear directory but in crypted directory there more files.

How can I get my all files in clear directory ?

**Comment by rfjakob** [comment] 2016-10-17 12:37
I will try to reproduce this today in the evening.

**Comment by systeme1** [comment] 2016-10-17 13:48
ok

**Comment by systeme1** [comment] 2016-10-17 17:58
For to try : 

Decrypted an encrypted directory not not empty

With your file manager, let rename this directory and stop the renaming in progress with the closed cross of file manager window.

let reencrypte the directory

let clear again and compare the files from clear diretory with the files of encrypted directory that shows the encrypted names.

Somes files do not appear in clear directory.

**Comment by rfjakob** [comment] 2016-10-17 22:58
Ok I checked what cryptkeeper is doing. It uses paranoia configuration.

I was unable to reproduce the lost files with clicking cancel. I could only reproduce this when killing encfs using `kill -9` while a rename is running. Did your computer or encfs crash during the rename?

Anyway, to recover the files, you have to create a new directory with the new name that you wanted for the rename. You remember it?

Then, in the encrypted directory, you **copy** the files that are missing in the "clear" directory to that new directory. In the encrypted form it will have name like `Qqq0DhaqnQ6PZXKl7bVWTrV` so make sure you get the right one.

All clear? I would recommend to make a copy of the whole encrypted directory if anything goes wrong!

**Comment by rfjakob** [comment] 2016-10-17 23:04
To find out which file in the "clear" directory is which file in the encrypted directory, you can use `ls -i1` to display the inode number. Example:

Plaintext (clear) view:
```
$ ls -i1
8399786 dir3
8402842 dir4
```

Encrypted:
```
$ ls -i1
8402842 6XW-6LsGevUDn64Y6IsBcO2K
8399786 gEBJWfuUcJAjzKCYuc8q1L7N
```

Now we see: 8399786 = dir3 = gEBJWfuUcJAjzKCYuc8q1L7N

**Comment by systeme1** [comment] 2016-10-18 06:25
Hi rfjakob !

Thank you for your work.

No crash during the renaming or later renaming.

I hope that I remember the name of directory !!!!!

I will try your method in the morning, or this afternoon. I will tell you the result.

**Comment by systeme1** [comment] 2016-10-18 09:45
Well,

Some precisions :

The tree of my directories in clear mode: 

.General → .Hidden1 → .Hidden2 → some directories (like dd1,dd2,...,ddx) → some files

I wanted rename '.General' using file manager Caja from Mate under Debian Jessie

I stop (it's a big mistake) before end of renaming.

Now some directories (like dd1, dd2, ddx) are missing in clear mode.


In encrypted mode I'm seeing all directories and files with encrypted name for each.

I dont know which directory directory create again with the name of renaming (.General) who was .Robert.

I know that it is not easy because my directory tree does not contain one directory.

**Comment by rfjakob** [comment] 2016-10-18 09:54
So, like this?
```
.Robert → .General → .Hidden1 → .Hidden2 → dd1,dd2,...,ddx
           ^^^^^^^
           Canceled rename
```
Do you know what you wanted to rename ".General" to?

**Comment by systeme1** [comment] 2016-10-18 11:28
Yes for the rename .General1 in .Robert

Do you know what you wanted to rename ".General" to? = I dont understand this question.

**Comment by rfjakob** [comment] 2016-10-18 21:24
Ok now I understand:
```
.General/.Hidden1/.Hidden2/dd1,dd2,...,ddx
^^^^^^^^
Canceled rename to ".Robert"
```
For the recovery, let's try this: Create the folders
```
.Robert/.Hidden1/.Hidden2
```
Then go into the encrypted version of ".Hidden2" and create a directory with one of the "lost" names. If it shows up in the plaintext we are good.

**Comment by systeme1** [comment] 2016-10-19 06:50
Sorry but the new clear directory is empty.

Is there a mark or code on a flie or directory for chain it  with its father-directory ?

**Comment by systeme1** [comment] 2016-10-19 07:05
Sorry, the clear .Robert/.Hidden1/.Hidden2 is empty.

**Comment by rfjakob** [comment] 2016-10-23 08:12
Hmm, I'm afraid it's gonna be quite hard to find out what happened here and how to recover it. How important is that data? Do you have a backup?

**Comment by systeme1** [comment] 2016-10-23 16:38
No backup alas.

How is a file related to his directory ?

The encrypted lost files are still present. Can connect to the old repertoire crypted ?

**Comment by rfjakob** [comment] 2016-10-23 21:53
The path to the file is used as an Initialization Vector (IV) for both the file name and the file content.
For the file contents, the actual IV is a combination of the file path and a value stored in each file header.

**Comment by rfjakob** [comment] 2016-10-23 21:56
Maybe reproducing it could be helpful. Create a new EncFS filesystem with one directory and lots of files in it. Rename it an cancel the rename. Can you trigger the issue again?

**Comment by systeme1** [comment] 2016-10-24 06:42
I have already experienced: it's the same result.

The no-decryptables files are present in the encrypted dirctory (I'm seeing it) but are not cleared by encfs.

Encfs ignores their.

Encfs must know which files to clear. Where is this information recorded ? In .xml files ?

**Comment by rfjakob** [comment] 2016-10-24 07:09
Ok, can you upload the test filesystem somewhere so I can look at it?

The first two bytes of the encrypted filename store a checksum. This is checked when decrypting the name, and if it is incorrect the file is ignored.

**Comment by rfjakob** [comment] 2016-10-24 07:36
Even better: Please create a `before.zip` with the test filesystem, and `after.zip` after you have triggered the issue.

**Comment by systeme1** [comment] 2016-10-24 10:58
How read the first two bytes of the encrypted filename and can we change this two bytes ?

**Comment by rfjakob** [comment] 2016-10-24 17:08
The first two bytes are base64-encoded in the first four characters of the filename, but changing them will not solve the problem because we don't know the correct value.

**Comment by samrocketman** [comment] 2017-07-02 18:43
Closing.  If you encounter the issue again, please open a _new issue_ and reference this one for context.  Thanks @benrubson!  If you think closing this is a mistake, then let me know and I'll re-evaluate.

**Closed by samrocketman** 2017-07-02 18:43 UTC
